In [1]:
import numpy as np
import pandas as pd

1. How likely is it that you roll doubles when rolling two dice?

In [50]:
#create our simulations
n_trials = 2 
n_simulations = 10_000

dice_rolls = np.random.randint(1, 7, size=(n_simulations, n_trials))
dice_rolls

array([[5, 5],
       [4, 6],
       [1, 2],
       ...,
       [1, 5],
       [4, 1],
       [4, 2]])

In [51]:
#Restructuring simulations
dice_rolls_transposed = dice_rolls.transpose()
dice_rolls_transposed

array([[5, 4, 1, ..., 1, 4, 4],
       [5, 6, 2, ..., 5, 1, 2]])

In [53]:
#Probability
(dice_rolls_transposed[0] == dice_rolls_transposed[1]).mean() 

0.1652

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [82]:
n_simulations = n_rows = 10_000
n_trials = n_columns =  8 

simulations = np.random.choice([1,0], size = (n_rows,n_columns)) # create simulations
simulations

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 1],
       ...,
       [0, 1, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [83]:
n_heads_per_simulation = simulations.sum(axis = 1)
n_heads_per_simulation #Calculate outcomes of the simulations

array([6, 4, 5, ..., 5, 0, 2])

In [84]:
exactly_3_heads = n_heads_per_simulation == 3
exactly_3_heads #Create booleans matching our condition

array([False, False, False, ..., False, False, False])

In [85]:
exactly_3_heads.mean() #Probability

0.215

What is the probability of getting more than 3 heads?

In [86]:
more_than_3 = n_heads_per_simulation > 3
more_than_3 #Create booleans matching our condition

array([ True,  True,  True, ...,  True, False, False])

In [87]:
more_than_3.mean() #Probability

0.6406

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [46]:
outcomes = [1, 0] #1 = web development and 0 = data science 

n_simulatios = 10_000
billboards = 2 

web_dev_prob = 0.75
data_science_prob = 0.25

billboard1 = np.random.choice(outcomes, size =(n_simulations, billboards), p=[web_dev_prob, data_science_prob])
billboard2 = np.random.choice(outcomes, size =(n_simulations, billboards), p=[web_dev_prob, data_science_prob])
#create our simulations               

In [47]:
both_boards_data = (billboard1 == [0,0]) & (billboard2 == [0,0])
both_boards_data #Create boolean matching our condition

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [48]:
both_boards_data.mean() #Probability

0.06485

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [103]:
n_simulations = n_rows = 10_000
n_days = n_columns = 4

simulation = np.random.normal(loc = 3, scale = 1.5, size = (n_rows, n_columns)).round()
simulation = np.where(simulation < 0, 0, simulation)
simulation #creating the simulation in pop tarts eaten per day

array([[1., 6., 0., 6.],
       [4., 2., 6., 3.],
       [0., 4., 2., 2.],
       ...,
       [4., 4., 4., 4.],
       [1., 3., 3., 2.],
       [5., 4., 4., 4.]])

In [104]:
sum_of_poptarts = simulation.sum(axis = 1)
sum_of_poptarts #summarizing simulation for poptarts eaten in a week

array([13., 15.,  8., ..., 16.,  9., 17.])

In [105]:
poptarts_available_friday = sum_of_poptarts < 17
poptarts_available_friday #create booleans for our condition

array([ True,  True,  True, ...,  True,  True, False])

In [107]:
poptarts_available_friday.mean() #probability

0.9318

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [33]:
# Generating our simulations
n_simulations = 10_000
male_height = np.random.normal(loc = 178, scale = 8, size = n_simulations)
female_height = np.random.normal(loc = 170, scale = 6, size = n_simulations)

In [108]:
#generating booleans for our condition
woman_taller_than_man = female_height > male_height 
#probability
woman_taller_than_man.mean()

0.2236

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [65]:
# Creating simulation

outcomes = [1, 0] #1 is corrupted, 0 is not corrupeted
n_simulations = n_rows = 10_000
n_students = n_columns = 50 

installation_fails = np.random.choice(outcomes, size = (n_rows, n_columns), p=[1/250, 249/250])
installation_fails

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [66]:
#Summarizing simulations, creating booleans
total_without_failures = installation_fails.sum(axis=1) < 1
total_without_failures

array([ True,  True,  True, ...,  True,  True,  True])

In [67]:
#Calculating probability
total_without_failures.mean()

0.8182

- 100 students?

In [68]:
#adjusting values and repeating
n_students = n_columns = 100
installation_fails = np.random.choice(outcomes, size = (n_rows, n_columns), p=[1/250, 249/250])
total_without_failures = installation_fails.sum(axis=1) < 1

In [69]:
# new probability
total_without_failures.mean()

0.6648

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [70]:
#adjusting values and repeating
n_students = n_columns = 150
installation_fails = np.random.choice(outcomes, size = (n_rows, n_columns), p=[1/250, 249/250])
total_with_failures = installation_fails.sum(axis=1) >= 1

In [71]:
# new probability
total_with_failures.mean()

0.4571


- How likely is it that 450 students all download anaconda without an issue?

In [72]:
#adjusting values and repeating
n_students = n_columns = 450
installation_fails = np.random.choice(outcomes, size = (n_rows, n_columns), p=[1/250, 249/250])
total_without_failures = installation_fails.sum(axis=1) < 1

In [73]:
# new probability
total_without_failures.mean()

0.1642

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [74]:
# Generating simulation
outcomes = [1, 0] # 1 = foodtruck shows, 0 = foodtruck doesn't show
n_simulations = n_rows = 10_000
n_days = n_columns = 3
probabilities = (.7, .3)

truck_wont_show = np.random.choice(outcomes, size = (n_rows, n_columns), p= probabilities)
truck_wont_show

array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       ...,
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 1]])

In [75]:
# Summarizing simulation
no_truck_three_days = truck_wont_show.sum(axis = 1)
no_truck_three_days

array([3, 3, 0, ..., 1, 2, 1])

In [76]:
# creating booleans to match condition
probability_of_no_show = no_truck_three_days == 0
probability_of_no_show

array([False, False,  True, ..., False, False, False])

In [77]:
# Calculating probability of how unlikely
probability_of_no_show.mean()

0.0277

- How likely is it that a food truck will show up sometime this week?

In [127]:
# Adjusting values to answer new question
n_days = n_columns = 5 
truck_will_show = np.random.choice(outcomes, size = (n_rows, n_columns), p= probabilities)
truck_shows_this_week = truck_will_show.sum(axis = 1) > 0 

In [128]:
#new probabilty 
truck_shows_this_week.mean()

0.9981

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?


In [123]:
# creatiing function to calculate odds

def odds_two_share_birthday(n_people):
    n_simulations = n_rows = 10_000
    days_of_year = list(range(1, 366))
    birthday = np.random.choice(days_of_year, size = (n_rows, n_people)) #creating simulation
    birthdays = pd.DataFrame(birthday) #converting to a dataframe
    return (birthdays.nunique(axis=1) < n_people).mean() #calculation to match our condition 



In [124]:
odds_two_share_birthday(23)

0.5108

In [125]:
odds_two_share_birthday(20)

0.4121

In [126]:
odds_two_share_birthday(40)

0.8912

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?
#class solution

In [132]:
simulations = np.random.randint(1, 366, size = (10_000, 23))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays: birthdays.nunique(), axis=1) < 23).mean() #23 people

0.5063

In [133]:
simulations = np.random.randint(1, 366, size = (10_000, 20))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays: birthdays.nunique(), axis=1) < 20).mean() #20 people

0.4064

In [134]:
simulations = np.random.randint(1, 366, size = (10_000, 40))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays: birthdays.nunique(), axis=1) < 40).mean() #40 people

0.894